project:
  type: website
  output-dir: docs

website:
  title: "Bletchley Weekly Drills"
  navbar:
    left:
      - href: "index.qmd"
        text: "About"
      - href: "examples/"
        text: "Examples"
  repo-url: https://github.com/flatiron-labs/ds-weekly-drills
  repo-actions: [source, issue]

format:
  html:
    theme: default
    toc: true