project:
  type: website
  output-dir: docs

website:
  title: "Bletchley Mastery Quests"
  navbar:
    left:
      - href: "index.qmd"
        text: "About"
      - href: "schedule/index.qmd"
        text: "Schedule"
      - href: "examples/index.qmd"
        text: "Examples"
  repo-url: https://github.com/flatiron-labs/ds-mastery-quests
  repo-actions: [source, issue]
  favicon: favicon.png

format:
  html:
    theme: 
      - flatly
      - styles.scss
    page-layout: full
    toc: true